export const extra = {
  id: {
    dashCsv: "Unduh Data CSV",
    qrModuleCta: "Buka Modul Orang Tua & Anak",
    gallery: {
      overline: "Galeri Digital Karyaku",
      title: "Sketsa-sketsa Rafa.",
      desc: "Visualisasi ruang isolasi emosional dari naskah film — digambar ulang sebagai seni garis yang melukis dirinya sendiri saat Anda menggulir.",
      items: [
        {
          tag: "Sosok Terbelenggu",
          title: "Terbelenggu Ekspektasi",
          desc: "Jeruji aturan sosial tentang definisi kekuatan seorang pria.",
        },
        {
          tag: "Bermulut Terkunci",
          title: "Suara yang Terkunci",
          desc: "Dogma kuno bahwa anak laki-laki dilarang cengeng dan mengeluh.",
        },
        {
          tag: "Gerbang Ruang Dialog",
          title: "Titik Balik",
          desc: "Fajar hangat yang mulai menyinari kamar gelap setelah penerimaan tulus sang Ayah.",
        },
      ],
    },
    remedies: {
      title: "Peta Perbaikan",
      note: "Dimensi yang perlu perhatian — beserta cara mengatasinya, langkah demi langkah.",
      allGood: "Semua dimensi tampak sehat — pertahankan ritme ini dan teruslah saling mendengar.",
      parent: {
        warmth: {
          label: "Membangun kehangatan",
          steps: [
            "Mulai hari dengan satu kalimat apresiasi yang spesifik, bukan basa-basi",
            "Tiru bahasanya: jika ia bercerita lewat gambar atau musik, masuklah lewat sana",
          ],
        },
        hostility: {
          label: "Meredam ledakan emosi",
          steps: [
            "Saat emosi naik, jeda 10 detik dan turunkan volume suara sebelum bicara",
            "Ganti bentakan dengan pertanyaan: \u201CApa yang terjadi?\u201D bukan \u201CKenapa kamu begitu?\u201D",
          ],
        },
        indifference: {
          label: "Menghadirkan diri",
          steps: [
            "Blokir 15 menit di kalender setiap hari bertuliskan namanya — tanpa ponsel",
            "Tanyakan satu detail kecil: temannya, gambarnya, atau lagu yang ia dengarkan hari ini",
          ],
        },
        rejection: {
          label: "Menerima tanpa syarat",
          steps: [
            "Pisahkan anak dari prestasinya: ucapkan bangga tanpa embel-embel nilai",
            "Katakan minggu ini: \u201CAyah/Ibu sayang kamu, apa pun yang terjadi.\u201D",
          ],
        },
      },
      son: {
        warmth: {
          label: "Merawat kehangatan",
          steps: [
            "Balas pelukan atau pujian itu dengan cerita — kehangatan tumbuh dua arah",
            "Ingat momen itu saat kamu ragu: kamu berharga",
          ],
        },
        hostility: {
          label: "Menghadapi bentakan",
          steps: [
            "Saat dibentak, tarik napas — reaksinya tentang emosinya, bukan tentang nilai dirimu",
            "Pilih waktu tenang untuk bilang: \u201CAku sedih kalau dibentak. Bisa bicara baik-baik?\u201D",
          ],
        },
        indifference: {
          label: "Saat merasa tak terlihat",
          steps: [
            "Tawarkan cerita lebih dulu: \u201CAyah/Bu, ada yang mau aku ceritakan sebentar\u201D",
            "Kalau tetap tak didengar, cari telinga lain: guru BK, kakak, atau kerabat",
          ],
        },
        rejection: {
          label: "Saat merasa jadi beban",
          steps: [
            "Tulis ini: perasaan itu nyata, tapi bukan fakta — kamu bukan beban",
            "Ceritakan perasaan ini ke orang dewasa tepercaya; kamu berhak dibantu",
          ],
        },
      },
    },
    module: {
      overline: "Modul Dialog",
      title: "Tujuh hari membuka kembali ruang.",
      desc: "Tujuh hari percakapan kecil untuk membangun kembali ruang bicara antara orang tua dan anak. Centang setiap hari yang selesai, lalu unduh modul ini untuk dibawa ke meja makan.",
      download: "Unduh Modul (PDF)",
      progress: (n) => `${n} dari 7 hari selesai`,
      day: (n) => `Hari ${n}`,
      forParent: "Untuk Orang Tua",
      forSon: "Untuk Anak",
      mark: "Tandai selesai",
      done: "Selesai",
      together: "Bersama",
      days: [
        {
          theme: "Membuka Pintu",
          parent: "Tanyakan satu hal tentang harinya, lalu dengarkan sampai selesai tanpa menasihati.",
          son: "Ceritakan satu hal kecil dari harimu — apa pun itu.",
        },
        {
          theme: "Bahasa Emosi",
          parent: "Sebutkan satu perasaan yang kamu lihat darinya hari ini, tanpa menghakimi: \u201CKamu tampak lelah\u2026\u201D",
          son: "Coba beri nama perasaanmu hari ini: senang, cemas, bangga, atau lelah?",
        },
        {
          theme: "Tanpa Pembanding",
          parent: "Seharian penuh tanpa kalimat pembanding. Ganti setiap dorongan membandingkan dengan pertanyaan.",
          son: "Tulis satu hal yang kamu sukai dari dirimu sendiri.",
        },
        {
          theme: "Ruang untuk Menangis",
          parent: "Katakan padanya: \u201CMenangis itu manusiawi. Ayah/Ibu juga pernah menangis.\u201D",
          son: "Izinkan dirimu merasakan hari ini — tanpa meminta maaf.",
        },
        {
          theme: "Apresiasi Kecil",
          parent: "Puji usahanya hari ini, bukan hasilnya.",
          son: "Ucapkan terima kasih untuk satu hal yang dilakukan orang tuamu.",
        },
        {
          theme: "Cerita Masa Kecil",
          parent: "Ceritakan satu kegagalanmu saat remaja dan apa yang kamu pelajari darinya.",
          son: "Tanyakan satu hal tentang masa remaja ayah atau ibumu.",
        },
        {
          theme: "Janji Ruang",
          parent: "Duduklah berdua dan sepakati satu ritual mingguan: makan bersama, jalan sore, atau sekadar mengobrol.",
          son: "Duduklah berdua dan sepakati satu ritual mingguan: makan bersama, jalan sore, atau sekadar mengobrol.",
        },
      ],
    },
    forum: {
      overline: "Forum Komunitas",
      title: "Ruang cerita bersama.",
      desc: "Ruang aman bagi orang tua dan keluarga untuk berbagi pengalaman membuka dialog dengan anak. Tanpa penghakiman — hanya sesama pejuang ruang bicara.",
      namePlaceholder: "Nama (boleh dikosongkan)",
      messagePlaceholder: "Ceritakan pengalaman Anda\u2026 (maks. 500 karakter)",
      submit: "Kirim Cerita",
      sending: "Mengirim\u2026",
      success: "Cerita Anda telah tampil. Terima kasih sudah berbagi.",
      error: "Gagal mengirim. Coba lagi.",
      tooShort: "Cerita minimal 5 karakter.",
      empty: "Belum ada cerita. Jadilah yang pertama berbagi.",
      hug: "Peluk",
      anonymous: "Orang Tua Anonim",
      pending: "Cerita Anda terkirim dan sedang menunggu persetujuan moderator. Terima kasih!",
      report: "Laporkan",
      reported: "Sudah dilaporkan",
    },
    contact: {
      overline: "Narahubung & Bantuan",
      title: "Butuh bicara lebih lanjut?",
      desc: "Jika hasil tes atau cerita di forum menyentuh sesuatu yang dalam, jangan dipendam. Hubungi layanan resmi berikut, atau tinggalkan pesan untuk tim Project Ruang.",
      hotlineTitle: "Layanan Resmi",
      hotlines: [
        { name: "SEJIWA — Kemenkes RI", number: "119 ext. 8", desc: "Konseling kesehatan jiwa dari Kementerian Kesehatan RI." },
        { name: "Halo Kemenkes", number: "1500-567", desc: "Layanan informasi dan darurat kesehatan 24 jam." },
        { name: "Into The Light Indonesia", number: "intothelightid.org", desc: "Komunitas pencegahan bunuh diri dan kesehatan mental remaja." },
      ],
      formTitle: "Pesan untuk Tim Project Ruang",
      namePh: "Nama Anda",
      contactPh: "WhatsApp / email (agar kami bisa membalas)",
      messagePh: "Ceritakan yang ingin Anda diskusikan\u2026 (min. 10 karakter)",
      submit: "Kirim Pesan",
      sending: "Mengirim\u2026",
      success: "Pesan terkirim. Tim kami akan menghubungi Anda.",
      error: "Gagal mengirim. Coba lagi.",
      tooShort: "Nama dan pesan (min. 10 karakter) wajib diisi.",
    },
    mod: {
      overline: "Area Tim",
      title: "Moderasi Forum",
      keyPh: "Kunci admin",
      unlock: "Buka",
      wrongKey: "Kunci salah.",
      back: "Kembali ke Beranda",
      pendingTitle: "Antrean Persetujuan",
      reportedTitle: "Cerita Dilaporkan",
      messagesTitle: "Pesan Narahubung Masuk",
      approve: "Setujui",
      reject: "Tolak",
      empty: "Tidak ada antrean.",
      emptyMsg: "Belum ada pesan masuk.",
      reports: "laporan",
    },
    dashByDayTitle: "Tes per Hari · 7 Hari Terakhir",
    resultEmail: {
      label: "Kirim hasil ini ke email Anda — untuk disimpan atau dibawa ke konselor.",
      placeholder: "nama@email.com",
      send: "Kirim ke Email",
      sending: "Mengirim\u2026",
      sent: "Terkirim! Silakan cek kotak masuk Anda.",
      error: "Gagal mengirim. Coba beberapa saat lagi.",
      invalid: "Format email tidak valid.",
    },
    treeVoice: {
      listen: "Dengarkan narasi",
      playing: "Sedang memutar\u2026",
      loading: "Menyiapkan suara\u2026",
    },
    dashByDayTitle: "Tes per Hari · 7 Hari Terakhir",
  },
  en: {
    dashCsv: "Download CSV Data",
    qrModuleCta: "Open the Parent & Son Module",
    gallery: {
      overline: "My Digital Gallery",
      title: "Rafa's sketches.",
      desc: "Visualizations of emotional isolation from the film's script — redrawn as line art that draws itself as you scroll.",
      items: [
        {
          tag: "Sosok Terbelenggu",
          title: "Shackled by Expectations",
          desc: "The bars of social rules about what a man's strength is supposed to mean.",
        },
        {
          tag: "Bermulut Terkunci",
          title: "A Locked Voice",
          desc: "The old dogma that boys are forbidden to be fragile or to complain.",
        },
        {
          tag: "Gerbang Ruang Dialog",
          title: "The Turning Point",
          desc: "A warm dawn beginning to light the dark room after a father's sincere acceptance.",
        },
      ],
    },
    remedies: {
      title: "The Repair Map",
      note: "Dimensions that need attention — with step-by-step ways to address them.",
      allGood: "Every dimension looks healthy — keep this rhythm and keep listening to each other.",
      parent: {
        warmth: {
          label: "Rebuilding warmth",
          steps: [
            "Start the day with one specific appreciation, not small talk",
            "Mirror his language: if he speaks through drawings or music, enter through there",
          ],
        },
        hostility: {
          label: "Cooling the flare-ups",
          steps: [
            "When anger rises, pause for 10 seconds and lower your voice before speaking",
            "Replace yelling with a question: \u201CWhat happened?\u201D instead of \u201CWhy are you like this?\u201D",
          ],
        },
        indifference: {
          label: "Showing up",
          steps: [
            "Block 15 minutes in your calendar every day with his name on it — no phone",
            "Ask one small detail: his friend, his drawing, or the song he played today",
          ],
        },
        rejection: {
          label: "Accepting without conditions",
          steps: [
            "Separate the child from the achievement: say you're proud with no grades attached",
            "Say this week: \u201CI love you, no matter what.\u201D",
          ],
        },
      },
      son: {
        warmth: {
          label: "Keeping the warmth alive",
          steps: [
            "Answer that hug or praise with a story — warmth grows both ways",
            "Remember that moment when you doubt yourself: you matter",
          ],
        },
        hostility: {
          label: "Facing the yelling",
          steps: [
            "When yelled at, breathe — their reaction is about their emotions, not your worth",
            "Pick a calm moment to say: \u201CIt hurts when I'm yelled at. Can we talk calmly?\u201D",
          ],
        },
        indifference: {
          label: "When you feel invisible",
          steps: [
            "Offer the story first: \u201CDad/Mom, there's something I want to tell you quickly\u201D",
            "If you're still unheard, find another ear: a school counselor, a sibling, or a relative",
          ],
        },
        rejection: {
          label: "When you feel like a burden",
          steps: [
            "Write this down: that feeling is real, but it is not a fact — you are not a burden",
            "Tell a trusted adult about this feeling; you deserve help",
          ],
        },
      },
    },
    module: {
      overline: "Dialogue Module",
      title: "Seven days to reopen the room.",
      desc: "Seven days of small conversations to rebuild the talking space between parent and son. Check off each completed day, then download this module to bring to the dinner table.",
      download: "Download Module (PDF)",
      progress: (n) => `${n} of 7 days completed`,
      day: (n) => `Day ${n}`,
      forParent: "For Parents",
      forSon: "For Sons",
      mark: "Mark as done",
      done: "Done",
      together: "Together",
      days: [
        {
          theme: "Opening the Door",
          parent: "Ask one thing about his day, then listen all the way through without advising.",
          son: "Share one small thing from your day — anything at all.",
        },
        {
          theme: "Emotional Language",
          parent: "Name one feeling you noticed in him today, without judging: \u201CYou look tired\u2026\u201D",
          son: "Try naming your feeling today: happy, anxious, proud, or tired?",
        },
        {
          theme: "No Comparisons",
          parent: "One full day without comparing sentences. Replace every urge to compare with a question.",
          son: "Write down one thing you like about yourself.",
        },
        {
          theme: "Room to Cry",
          parent: "Tell him: \u201CCrying is human. I've cried too.\u201D",
          son: "Allow yourself to feel today — without apologizing.",
        },
        {
          theme: "Small Appreciation",
          parent: "Praise his effort today, not the result.",
          son: "Thank your parents for one thing they did.",
        },
        {
          theme: "Childhood Stories",
          parent: "Share one failure from your teenage years and what you learned from it.",
          son: "Ask one thing about your dad's or mom's teenage years.",
        },
        {
          theme: "The Ruang Promise",
          parent: "Sit together and agree on one weekly ritual: a meal, an evening walk, or simply talking.",
          son: "Sit together and agree on one weekly ritual: a meal, an evening walk, or simply talking.",
        },
      ],
    },
    forum: {
      overline: "Community Forum",
      title: "A shared storytelling space.",
      desc: "A safe space for parents and families to share their experiences of opening dialogue with their children. No judgment — only fellow fighters for the talking space.",
      namePlaceholder: "Name (optional)",
      messagePlaceholder: "Share your experience\u2026 (max. 500 characters)",
      submit: "Share Story",
      sending: "Sending\u2026",
      success: "Your story is now live. Thank you for sharing.",
      error: "Failed to send. Please try again.",
      tooShort: "Stories need at least 5 characters.",
      empty: "No stories yet. Be the first to share.",
      hug: "Hug",
      anonymous: "Anonymous Parent",
      pending: "Your story was sent and is now awaiting moderator approval. Thank you!",
      report: "Report",
      reported: "Reported",
    },
    contact: {
      overline: "Contact & Support",
      title: "Need to talk further?",
      desc: "If the test result or a forum story touched something deep, don't keep it inside. Reach out to the official services below, or leave a message for the Project Ruang team.",
      hotlineTitle: "Official Services",
      hotlines: [
        { name: "SEJIWA — Ministry of Health", number: "119 ext. 8", desc: "Mental health counseling from the Indonesian Ministry of Health." },
        { name: "Halo Kemenkes", number: "1500-567", desc: "24-hour health information and emergency line." },
        { name: "Into The Light Indonesia", number: "intothelightid.org", desc: "Community for suicide prevention and youth mental health." },
      ],
      formTitle: "Message the Project Ruang Team",
      namePh: "Your name",
      contactPh: "WhatsApp / email (so we can reply)",
      messagePh: "Tell us what you'd like to discuss\u2026 (min. 10 characters)",
      submit: "Send Message",
      sending: "Sending\u2026",
      success: "Message sent. Our team will reach out to you.",
      error: "Failed to send. Please try again.",
      tooShort: "Name and message (min. 10 characters) are required.",
    },
    mod: {
      overline: "Team Area",
      title: "Forum Moderation",
      keyPh: "Admin key",
      unlock: "Unlock",
      wrongKey: "Wrong key.",
      back: "Back to Home",
      pendingTitle: "Approval Queue",
      reportedTitle: "Reported Stories",
      messagesTitle: "Incoming Contact Messages",
      approve: "Approve",
      reject: "Reject",
      empty: "Nothing in the queue.",
      emptyMsg: "No messages yet.",
      reports: "reports",
    },
    resultEmail: {
      label: "Send this result to your email — to keep or to bring to a counselor.",
      placeholder: "name@email.com",
      send: "Send to Email",
      sending: "Sending\u2026",
      sent: "Sent! Please check your inbox.",
      error: "Failed to send. Please try again shortly.",
      invalid: "Invalid email format.",
    },
    treeVoice: {
      listen: "Listen to narration",
      playing: "Now playing\u2026",
      loading: "Preparing voice\u2026",
    },
    dashByDayTitle: "Tests per Day · Last 7 Days",
  },
};
